export type SpssMegaWorkflow = {
  id: string;
  category: string;
  title: string;
  examUse: string;
  useWhen: string[];
  variables: string[];
  menuPath: string[];
  setup: string[];
  options: string[];
  output: string[];
  report: string[];
  examSentence: string;
  traps: string[];
  sourceRefs: string[];
};

export type SpssDecisionRow = {
  question: string;
  variables: string;
  test: string;
  spssPath: string;
  output: string;
};

export const spssMegaCategories = [
  "Data prep and safety",
  "Descriptives and normality",
  "Means and t-tests",
  "Proportions and chi-square",
  "Non-parametric tests",
  "Correlation and linear regression",
  "Mediation, interaction and outliers",
  "Binary logistic regression",
];

export const spssDecisionRows: SpssDecisionRow[] = [
  {
    question: "Describe a categorical variable",
    variables: "One categorical variable",
    test: "Frequencies",
    spssPath: "Analyze > Descriptive Statistics > Frequencies",
    output: "Frequency, Percent, Valid Percent",
  },
  {
    question: "Describe a numerical variable",
    variables: "One continuous or scale variable",
    test: "Frequencies with Statistics, or Explore",
    spssPath: "Analyze > Descriptive Statistics > Frequencies / Explore",
    output: "Mean, SD, median, range, CI, histogram",
  },
  {
    question: "Mean compared with a known value",
    variables: "One continuous outcome",
    test: "One-sample t-test",
    spssPath: "Analyze > Compare Means > One-Sample T Test",
    output: "One-Sample Test: t, df, Sig., mean difference, CI",
  },
  {
    question: "Mean in two unrelated groups",
    variables: "Continuous outcome + binary group",
    test: "Independent samples t-test",
    spssPath: "Analyze > Compare Means > Independent-Samples T Test",
    output: "Levene's test, t-test row, p-value, mean difference",
  },
  {
    question: "Mean before versus after in same people",
    variables: "Two continuous paired measurements",
    test: "Paired samples t-test",
    spssPath: "Analyze > Compare Means > Paired-Samples T Test",
    output: "Paired Samples Test: t, df, Sig., CI",
  },
  {
    question: "One categorical proportion versus expected value",
    variables: "One categorical variable",
    test: "One-sample chi-square, exact if assumptions fail",
    spssPath: "Analyze > Nonparametric Tests > Legacy Dialogs > Chi-Square",
    output: "Test Statistics: chi-square, df, Asymp. Sig. or Exact Sig.",
  },
  {
    question: "Two categorical variables / compare proportions",
    variables: "Two categorical variables",
    test: "Pearson chi-square; Fisher/exact if assumptions fail",
    spssPath: "Analyze > Descriptive Statistics > Crosstabs",
    output: "Crosstab percentages, Pearson Chi-Square, Fisher's Exact",
  },
  {
    question: "Before-after categorical change",
    variables: "Two paired categorical variables",
    test: "McNemar test",
    spssPath: "Analyze > Descriptive Statistics > Crosstabs",
    output: "McNemar p-value",
  },
  {
    question: "Skewed/ordinal one-sample median",
    variables: "One skewed continuous or ordinal variable",
    test: "Wilcoxon signed-rank test",
    spssPath: "Analyze > Nonparametric Tests > One Sample",
    output: "Test Summary / double-click table: Z and p-value",
  },
  {
    question: "Skewed/ordinal two unrelated groups",
    variables: "Skewed continuous or ordinal outcome + binary group",
    test: "Mann-Whitney U test",
    spssPath: "Analyze > Nonparametric Tests > Independent Samples",
    output: "Mann-Whitney U, Z, p-value",
  },
  {
    question: "Skewed/ordinal before-after in same people",
    variables: "Two paired skewed continuous or ordinal measurements",
    test: "Related-samples Wilcoxon signed-rank test",
    spssPath: "Analyze > Nonparametric Tests > Related Samples",
    output: "Wilcoxon matched-pair signed-rank p-value",
  },
  {
    question: "Two continuous variables move together",
    variables: "Two continuous variables",
    test: "Pearson correlation if roughly normal; Spearman if skewed/ordinal",
    spssPath: "Analyze > Correlate > Bivariate",
    output: "Correlation coefficient r or rho, Sig.",
  },
  {
    question: "Continuous outcome predicted by one or more variables",
    variables: "Continuous outcome + predictor(s)",
    test: "Linear regression",
    spssPath: "Analyze > Regression > Linear",
    output: "Model Summary, ANOVA, Coefficients",
  },
  {
    question: "Binary yes/no outcome predicted by variables",
    variables: "Binary outcome + predictor(s)",
    test: "Binary logistic regression",
    spssPath: "Analyze > Regression > Binary Logistic",
    output: "Omnibus, Nagelkerke R2, Variables in the Equation, Exp(B)",
  },
];

export const spssLastMinuteRules = [
  "First identify the outcome variable. The outcome decides the family of test.",
  "Continuous outcome usually means t-test or linear regression.",
  "Categorical outcome usually means chi-square or logistic regression.",
  "Binary outcome plus prediction or adjustment means binary logistic regression.",
  "Paired wording means the same people measured twice, matched pairs, twins, or before-after.",
  "Turn Split File off before running the final test unless the question explicitly asks for subgroup output.",
  "For odds ratio interpretation in logistic regression, use Exp(B), not B.",
  "For confidence intervals around ratios, compare with 1. For confidence intervals around mean differences or regression slopes, compare with 0.",
  "For Hosmer-Lemeshow, p > .05 is the reassuring result.",
];

export const spssMegaWorkflows: SpssMegaWorkflow[] = [
  {
    id: "turn-off-split-file",
    category: "Data prep and safety",
    title: "Reset Split File before final analysis",
    examUse: "Use this whenever you previously checked histograms by group. It prevents SPSS from accidentally running every later output separately.",
    useWhen: ["You used Split File to inspect normality by gender/group.", "Your output is unexpectedly repeated by group."],
    variables: ["Grouping variable used earlier, such as gender."],
    menuPath: ["Data", "Split File"],
    setup: ["Choose 'Analyze all cases, do not create groups'.", "Click OK.", "Re-run the final test only after Split File is off."],
    options: ["Only leave Split File on when the exam explicitly asks for separate output by group."],
    output: ["No output table is needed. This is a safety step."],
    report: ["Do not report Split File itself. Use it only to check assumptions or separate descriptive output."],
    examSentence: "Split File was turned off before the inferential test so the analysis used the full sample.",
    traps: ["Forgetting Split File is on and interpreting subgroup tests as if they were the whole sample."],
    sourceRefs: ["32-t-tests.pdf p19-p22", "15-lecture 5 .pdf p14-p17"],
  },
  {
    id: "compute-variable",
    category: "Data prep and safety",
    title: "Compute a new variable",
    examUse: "Use this for paired difference scores, interaction terms, products, or any new calculated variable.",
    useWhen: ["The question asks for a difference, such as before minus after.", "You need an interaction term such as height_x_sex.", "You need a product term for moderation."],
    variables: ["Existing variables used in the calculation."],
    menuPath: ["Transform", "Compute Variable"],
    setup: [
      "Type the new variable name in Target Variable.",
      "Build the formula in Numeric Expression.",
      "Use minus for difference scores and * for product/interaction terms.",
      "Click OK and check the new column appears in Data View.",
    ],
    options: ["Use clear names: diffweight, height_x_sex, pov_x_low."],
    output: ["The new variable appears in the data set. There may be no important output table."],
    report: ["For paired tests, check the distribution of the difference variable before choosing paired t-test versus Wilcoxon."],
    examSentence: "A new variable was computed as [variable A] minus [variable B] before checking the distribution of the difference.",
    traps: ["Checking normality of the two raw paired variables instead of the difference score.", "Typing a name with spaces or symbols SPSS will not accept."],
    sourceRefs: ["32-t-tests.pdf p30-p31", "27-lecture 9-1.pdf p10", "01-Lecture 9 Chunk 2.pdf p9/p15/p21"],
  },
  {
    id: "dummy-recode",
    category: "Data prep and safety",
    title: "Make dummy variables from a categorical predictor",
    examUse: "Use this before regression when a categorical predictor has more than two groups.",
    useWhen: ["A predictor has 3+ categories, such as Low/Medium/High urbanicity.", "The lecture asks for dummy variables or reference category."],
    variables: ["Original categorical predictor.", "Reference group that will not get its own dummy variable."],
    menuPath: ["Transform", "Recode into Different Variables"],
    setup: [
      "Move the original variable into the input box.",
      "Give the new dummy variable an output name and click Change.",
      "Open Old and New Values.",
      "Code the target category as 1.",
      "Code all other values as 0.",
      "Repeat until you have k - 1 dummy variables for k categories.",
    ],
    options: ["Leave one category out as the reference category.", "For Low/Medium/High, create Low and Medium dummies if High is the reference."],
    output: ["New 0/1 dummy columns in the data set."],
    report: ["Each dummy coefficient compares that category with the omitted reference group."],
    examSentence: "With three categories, create two dummy variables; the omitted category is the reference group.",
    traps: ["Creating a dummy for every category. That gives no reference group.", "Forgetting that the coefficient is compared with the omitted category."],
    sourceRefs: ["19-Lecture 6 Chunk 3.pdf p27-p30", "01-Lecture 9 Chunk 2.pdf p3-p8"],
  },
  {
    id: "select-cases-outlier",
    category: "Data prep and safety",
    title: "Select Cases to rerun without an outlier",
    examUse: "Use this when the lecture asks whether one case is influencing the regression result.",
    useWhen: ["The question names a possible outlier, such as DC state.", "You need to compare a model with and without a case."],
    variables: ["Case identifier variable.", "Outcome and predictor variables for the regression."],
    menuPath: ["Data", "Select Cases"],
    setup: ["Choose the condition that excludes the outlier.", "Filter or remove the selected case for the analysis.", "Rerun the same regression model."],
    options: ["Keep a note of which model includes all data and which excludes the outlier."],
    output: ["Compare Coefficients and Model Summary across the two runs."],
    report: ["If the coefficient changes a lot after excluding the case, the case may be influential."],
    examSentence: "The model was rerun excluding the potential outlier to assess influence on the regression coefficient.",
    traps: ["Deleting data permanently instead of filtering/selecting cases.", "Changing the model at the same time, which makes the comparison unclear."],
    sourceRefs: ["02-lecture 9 Chunk 3 QAC.pdf p15-p17"],
  },
  {
    id: "frequencies-categorical",
    category: "Descriptives and normality",
    title: "Frequencies for categorical variables",
    examUse: "Use this to describe nominal or ordinal variables and get counts/percentages.",
    useWhen: ["One variable is categorical.", "You need N and percentages for each category.", "You need a bar chart or pie chart."],
    variables: ["Categorical variable, such as gender, ethnicity, age group, smoker yes/no."],
    menuPath: ["Analyze", "Descriptive Statistics", "Frequencies"],
    setup: ["Move the variable into Variable(s).", "Keep Display frequency tables on.", "Click OK."],
    options: ["Charts: choose Bar Chart or Pie Chart for categorical displays."],
    output: ["Frequency table.", "Frequency, Percent, Valid Percent, Cumulative Percent."],
    report: ["Use Valid Percent if there are missing values and the exam wants percentage among valid cases."],
    examSentence: "There were [N] participants in [category], representing [percent]% of valid cases.",
    traps: ["Using a histogram for categories.", "Confusing Percent with Valid Percent when missing values exist."],
    sourceRefs: ["05-Lecture 1 Chunk 3.pdf p8-p10"],
  },
  {
    id: "numerical-descriptives-histogram",
    category: "Descriptives and normality",
    title: "Numerical descriptives and histogram",
    examUse: "Use this to get mean, SD, median, range and a quick normality check.",
    useWhen: ["One variable is continuous/scale.", "You need mean and SD.", "You need to check whether the distribution looks roughly symmetric."],
    variables: ["Continuous variable, such as height, weight, score, income."],
    menuPath: ["Analyze", "Descriptive Statistics", "Frequencies"],
    setup: [
      "Move the numerical variable into Variable(s).",
      "Untick Display frequency tables if the variable has many values.",
      "Click Statistics and choose the descriptive indices needed.",
      "Click Charts and choose Histogram.",
    ],
    options: ["Tick 'Show normal curve' for a histogram normality check.", "Ask for mean, median, mode, SD, minimum, maximum and quartiles if needed."],
    output: ["Statistics table.", "Histogram.", "Minimum and maximum for data checking."],
    report: ["For roughly symmetric data, report mean and SD. For skewed data, report median and IQR."],
    examSentence: "The mean [variable] was [mean] with a standard deviation of [SD]. The histogram was [roughly symmetric/skewed].",
    traps: ["Automatically using mean and SD for heavily skewed data.", "Leaving huge frequency tables on for continuous variables."],
    sourceRefs: ["06-Lecture 1 Chunk 4.pdf p13-p14", "02-lecture 9 Chunk 3 QAC.pdf p6"],
  },
  {
    id: "explore-confidence-interval",
    category: "Descriptives and normality",
    title: "Explore for confidence interval around a mean",
    examUse: "Use this when the exam asks for a confidence interval for one numerical variable.",
    useWhen: ["You need the 95% CI for a sample mean.", "The lecture wording says compute CI in SPSS."],
    variables: ["Continuous variable."],
    menuPath: ["Analyze", "Descriptive Statistics", "Explore"],
    setup: ["Put the variable into Dependent List.", "Click Statistics.", "Change the confidence interval level if needed.", "Click Continue and OK."],
    options: ["Default is usually 95% confidence interval."],
    output: ["Descriptives table.", "Mean and lower/upper bound of the CI."],
    report: ["Report the lower and upper bounds in the units of the variable."],
    examSentence: "The estimated mean was [mean], with a 95% confidence interval from [lower] to [upper].",
    traps: ["Reading minimum and maximum as if they were the confidence interval."],
    sourceRefs: ["09-Lecture 2 Chunk 3 .pdf p12"],
  },
  {
    id: "boxplot-by-group",
    category: "Descriptives and normality",
    title: "Boxplot by group",
    examUse: "Use this to visually compare a numerical variable across groups and spot possible outliers.",
    useWhen: ["Continuous outcome compared across categories.", "You need medians/IQRs or possible outliers by group."],
    variables: ["Continuous variable.", "Grouping variable."],
    menuPath: ["Graphs", "Legacy Dialogs", "Boxplot"],
    setup: ["Choose Simple layout.", "Click Define.", "Put the numerical variable into Variable.", "Put the group into Category Axis.", "Click OK."],
    options: ["Use before a group comparison when shape/outliers matter."],
    output: ["Boxplot with median, IQR and possible outlier markers."],
    report: ["Use the plot to decide whether outliers or skew make a non-parametric test more appropriate."],
    examSentence: "The boxplot suggested [similar/different] medians and [no obvious/possible] outliers across groups.",
    traps: ["Using a bar chart for a continuous outcome when a boxplot would show spread and outliers."],
    sourceRefs: ["06-Lecture 1 Chunk 4.pdf p28"],
  },
  {
    id: "one-sample-t",
    category: "Means and t-tests",
    title: "One-sample t-test",
    examUse: "Use this when one sample mean is compared with a known or hypothesized value.",
    useWhen: ["Outcome is continuous.", "Question asks whether the population mean equals a fixed value, such as 66 kg or 40000."],
    variables: ["One continuous outcome.", "Known test value."],
    menuPath: ["Analyze", "Compare Means", "One-Sample T Test"],
    setup: ["Move the outcome into Test Variable(s).", "Enter the known value in Test Value.", "Click OK."],
    options: ["Check the distribution first if asked. The outcome should be roughly symmetric for the t-test."],
    output: ["One-Sample Statistics.", "One-Sample Test: t, df, Sig. (2-tailed), mean difference, CI."],
    report: ["Use the p-value to decide whether the mean differs from the test value."],
    examSentence: "A one-sample t-test showed that the mean was [significantly/not significantly] different from [test value], t([df]) = [t], p = [p].",
    traps: ["Putting the known value in the data sheet instead of the Test Value box.", "Reporting the descriptive table but ignoring the One-Sample Test table."],
    sourceRefs: ["12-Lecture 3 chunk 3.pdf p6-p10", "32-t-tests.pdf p14"],
  },
  {
    id: "independent-samples-t",
    category: "Means and t-tests",
    title: "Independent samples t-test",
    examUse: "Use this when comparing the mean of a continuous outcome between two unrelated groups.",
    useWhen: ["Outcome is continuous.", "Group variable is binary.", "People in group A are not the same people as group B."],
    variables: ["Continuous test variable.", "Binary grouping variable."],
    menuPath: ["Analyze", "Compare Means", "Independent-Samples T Test"],
    setup: [
      "Move the continuous outcome into Test Variable(s).",
      "Move the group variable into Grouping Variable.",
      "Click Define Groups and enter the two group codes used in the data.",
      "Click Continue and OK.",
    ],
    options: ["Before the final test, use Split File only to check histograms by group, then turn Split File off."],
    output: ["Group Statistics.", "Independent Samples Test.", "Levene's Test.", "t-test for Equality of Means."],
    report: ["If Levene's p > .05, use Equal variances assumed. If Levene's p < .05, use Equal variances not assumed."],
    examSentence: "An independent samples t-test showed that mean [outcome] was [higher/lower/not different] in [group A] than [group B], t([df]) = [t], p = [p].",
    traps: ["Forgetting Define Groups.", "Leaving Split File on.", "Using the wrong t-test row after Levene's test."],
    sourceRefs: ["32-t-tests.pdf p19-p23"],
  },
  {
    id: "paired-samples-t",
    category: "Means and t-tests",
    title: "Paired samples t-test",
    examUse: "Use this for before-after means or matched continuous measurements.",
    useWhen: ["Same people measured twice.", "Matched pairs, twins, or before-after design.", "Outcome is continuous and the difference is roughly symmetric."],
    variables: ["Continuous before variable.", "Continuous after variable.", "Optional difference variable for normality check."],
    menuPath: ["Analyze", "Compare Means", "Paired-Samples T Test"],
    setup: ["Move the two paired variables into Paired Variable(s).", "Make sure the pair direction matches the interpretation.", "Click OK."],
    options: ["Use Transform > Compute Variable to create before minus after if you need to check the distribution of differences."],
    output: ["Paired Samples Statistics.", "Paired Samples Test: mean difference, t, df, Sig., CI."],
    report: ["Interpret the mean difference in the direction SPSS used."],
    examSentence: "A paired samples t-test showed that [before/after] values were [significantly/not significantly] different, t([df]) = [t], p = [p].",
    traps: ["Treating paired data as independent.", "Checking normality of each raw variable instead of the paired difference."],
    sourceRefs: ["32-t-tests.pdf p30-p33"],
  },
  {
    id: "one-sample-chi-square",
    category: "Proportions and chi-square",
    title: "One-sample chi-square test",
    examUse: "Use this when one categorical variable is compared with expected proportions.",
    useWhen: ["One categorical variable.", "Question asks whether categories occur equally or according to a stated proportion."],
    variables: ["One categorical variable.", "Expected proportions if not equal."],
    menuPath: ["Analyze", "Nonparametric Tests", "Legacy Dialogs", "Chi-Square"],
    setup: ["Move the variable into Test Variable List.", "Choose all categories equal, or choose Values and enter expected values in coding order.", "Click OK."],
    options: ["Use Exact if the expected-count assumptions are violated."],
    output: ["Test Statistics table.", "Chi-Square, df, Asymp. Sig. or Exact Sig."],
    report: ["Use the p-value to decide whether observed proportions differ from expected proportions."],
    examSentence: "The observed proportions were [significantly/not significantly] different from the expected proportions, chi-square([df]) = [value], p = [p].",
    traps: ["Entering expected values in the wrong category order.", "Ignoring expected-count assumptions."],
    sourceRefs: ["12-Lecture 3 chunk 3.pdf p12-p15", "14-lecture 4.pdf p10-p12", "16-Lecture 5 part 2 .pdf p7-p9"],
  },
  {
    id: "crosstabs-pearson-chi-square",
    category: "Proportions and chi-square",
    title: "Crosstabs with Pearson chi-square",
    examUse: "Use this for association between two categorical variables or comparing proportions between groups.",
    useWhen: ["Two categorical variables.", "Question asks whether proportions differ by group.", "Example: smoker status by low birthweight."],
    variables: ["Row variable: usually exposure/group.", "Column variable: usually outcome."],
    menuPath: ["Analyze", "Descriptive Statistics", "Crosstabs"],
    setup: ["Put the exposure/group variable in Rows.", "Put the outcome variable in Columns.", "Click Statistics and tick Chi-square.", "Click Cells and tick Observed plus row or column percentages.", "Click OK."],
    options: ["Choose row or column percentages based on the wording. If the sentence says 'of those with outcome', use the outcome denominator."],
    output: ["Crosstabulation table.", "Chi-Square Tests table.", "Pearson Chi-Square value, df and p-value.", "Expected counts for assumptions."],
    report: ["Use Pearson's Chi-Square when assumptions hold."],
    examSentence: "There was a [significant/non-significant] association between [row variable] and [column variable], chi-square([df]) = [value], p = [p].",
    traps: ["Using the wrong denominator for percentages.", "Reporting Fisher's exact when Pearson's assumptions are fine, or vice versa."],
    sourceRefs: ["14-lecture 4.pdf p15-p18", "16-Lecture 5 part 2 .pdf p12-p16", "28-Lecture 10-1.pdf p9-p14"],
  },
  {
    id: "fisher-exact",
    category: "Proportions and chi-square",
    title: "Exact tests and Fisher's exact",
    examUse: "Use this when chi-square expected-count assumptions fail.",
    useWhen: ["Expected counts are too small.", "2x2 table with small counts.", "2xP table where exact option is needed."],
    variables: ["Categorical row variable.", "Categorical column variable."],
    menuPath: ["Analyze", "Descriptive Statistics", "Crosstabs", "Exact"],
    setup: ["Set up Crosstabs as usual.", "Click Statistics and select Chi-square.", "Click Exact.", "Choose Exact.", "Click Continue and OK."],
    options: ["In a 2x2 table, SPSS may display Fisher's Exact automatically. In a 2xP table, use the Exact tab."],
    output: ["Chi-Square Tests table.", "Fisher's Exact Test or Exact Sig."],
    report: ["Report exact/Fisher p-value when Pearson chi-square assumptions do not hold."],
    examSentence: "Because expected counts were small, Fisher's exact/exact p-value was used; p = [p].",
    traps: ["Using Pearson's p-value even after the output warns that expected counts are too small."],
    sourceRefs: ["16-Lecture 5 part 2 .pdf p5-p16"],
  },
  {
    id: "risk-estimates-crosstabs",
    category: "Proportions and chi-square",
    title: "Risk estimates, odds ratio and risk ratio from Crosstabs",
    examUse: "Use this when the exam asks for risk, odds, odds ratio, risk ratio or relative risk from a 2x2 table.",
    useWhen: ["Two binary categorical variables.", "Outcome is yes/no.", "Question asks for risk or odds."],
    variables: ["Row: exposure/group.", "Column: outcome."],
    menuPath: ["Analyze", "Descriptive Statistics", "Crosstabs", "Statistics"],
    setup: ["Put exposure/group in Rows.", "Put outcome in Columns.", "Click Statistics.", "Tick Chi-square and Risk.", "Click Cells and request Observed plus appropriate percentages."],
    options: ["Make sure the event category is the one you intend to interpret."],
    output: ["Risk Estimate table.", "Odds Ratio.", "Relative Risk / Risk Ratio.", "Confidence intervals."],
    report: ["Risk = event / total. Odds = event / non-event. OR and RR confidence intervals are judged against 1."],
    examSentence: "The odds of [event] were [OR] times [higher/lower] in [exposed] compared with [reference].",
    traps: ["Confusing risk with odds.", "Using the non-event column as if it were the event column."],
    sourceRefs: ["28-Lecture 10-1.pdf p20-p25"],
  },
  {
    id: "mcnemar",
    category: "Proportions and chi-square",
    title: "McNemar test for paired categorical data",
    examUse: "Use this when the same participants have a binary/category response before and after.",
    useWhen: ["Two paired categorical variables.", "Before-after yes/no.", "Matched categorical outcome."],
    variables: ["Before categorical variable.", "After categorical variable."],
    menuPath: ["Analyze", "Descriptive Statistics", "Crosstabs"],
    setup: ["Put the before variable in Rows.", "Put the after variable in Columns.", "Click Statistics.", "Tick McNemar.", "Click Continue and OK."],
    options: ["Cells: Observed counts are usually enough; percentages can help interpretation."],
    output: ["Crosstab table.", "McNemar Test table.", "p-value."],
    report: ["Use McNemar p-value for paired proportions, not Pearson chi-square."],
    examSentence: "McNemar's test showed that the paired proportions [changed/did not change] significantly, p = [p].",
    traps: ["Using Pearson chi-square for before-after data from the same people."],
    sourceRefs: ["14-lecture 4.pdf p27", "16-Lecture 5 part 2 .pdf p19-p21"],
  },
  {
    id: "wilcoxon-one-sample",
    category: "Non-parametric tests",
    title: "One-sample Wilcoxon signed-rank test",
    examUse: "Use this as the non-parametric alternative to a one-sample t-test.",
    useWhen: ["One skewed continuous or ordinal variable.", "Question asks whether the median equals a fixed value."],
    variables: ["One test field.", "Hypothesized median."],
    menuPath: ["Analyze", "Nonparametric Tests", "One Sample"],
    setup: ["Click Fields.", "Add the outcome to Test Fields.", "Enter the hypothesized median.", "Run the Wilcoxon signed-rank test."],
    options: ["Check histogram/descriptives first if the question asks why non-parametric is used."],
    output: ["Test Summary.", "Detailed table after double-click: Z and p-value."],
    report: ["Interpret as median significantly different or not different from the hypothesized value."],
    examSentence: "The one-sample Wilcoxon signed-rank test indicated that the median was [not/significantly] different from [value], Z = [Z], p = [p].",
    traps: ["Calling it a mean test. Wilcoxon is about median/ranks in this course context."],
    sourceRefs: ["15-lecture 5 .pdf p7-p12"],
  },
  {
    id: "mann-whitney",
    category: "Non-parametric tests",
    title: "Mann-Whitney U test",
    examUse: "Use this as the non-parametric alternative to independent samples t-test.",
    useWhen: ["Outcome is skewed continuous, ordinal or discrete.", "Two independent groups."],
    variables: ["Outcome in Test Fields.", "Binary grouping variable in Groups."],
    menuPath: ["Analyze", "Nonparametric Tests", "Independent Samples"],
    setup: ["Click Fields.", "Put the outcome in Test Fields.", "Put the group in Groups.", "Click Settings.", "Choose Customize tests.", "Select Mann-Whitney U.", "Run."],
    options: ["Use Split File only to inspect histograms by group, then turn it off."],
    output: ["Hypothesis Test Summary.", "Mann-Whitney U, Z and p-value if expanded."],
    report: ["Interpret group difference in distributions/median ranks."],
    examSentence: "A Mann-Whitney U test showed that [outcome] was [significantly/not significantly] different between [group A] and [group B], U = [U], p = [p].",
    traps: ["Using independent t-test when the lecture scenario says assumptions are violated."],
    sourceRefs: ["15-lecture 5 .pdf p14-p20"],
  },
  {
    id: "wilcoxon-related",
    category: "Non-parametric tests",
    title: "Related-samples Wilcoxon signed-rank test",
    examUse: "Use this as the non-parametric alternative to paired samples t-test.",
    useWhen: ["Same people measured twice.", "Difference scores are skewed or ordinal."],
    variables: ["Before variable.", "After variable."],
    menuPath: ["Analyze", "Nonparametric Tests", "Related Samples"],
    setup: ["Click Fields.", "Add both paired variables to Test Fields.", "Click Settings.", "Choose Customize tests.", "Select Wilcoxon matched-pair signed-rank.", "Run."],
    options: ["The lecture sometimes calls this Wilcoxon sum/signed rank for paired samples; in SPSS choose related samples Wilcoxon matched-pair signed-rank."],
    output: ["Hypothesis Test Summary.", "Wilcoxon signed-rank p-value."],
    report: ["Interpret whether the paired values changed significantly."],
    examSentence: "A related-samples Wilcoxon signed-rank test showed that [before] and [after] were [significantly/not significantly] different, p = [p].",
    traps: ["Using Mann-Whitney for paired data."],
    sourceRefs: ["15-lecture 5 .pdf p24-p26"],
  },
  {
    id: "scatterplot",
    category: "Correlation and linear regression",
    title: "Scatterplot for two continuous variables",
    examUse: "Use this before correlation/regression to check linearity and outliers.",
    useWhen: ["Both variables are continuous.", "You need to visually assess direction, strength and linearity."],
    variables: ["Continuous predictor on x-axis.", "Continuous outcome on y-axis."],
    menuPath: ["Graphs", "Legacy Dialogs", "Scatter/Dot"],
    setup: ["Choose Simple Scatter.", "Click Define.", "Put dependent variable in Y Axis.", "Put independent variable in X Axis.", "Optionally label cases by ID.", "Click OK."],
    options: ["Use Label Cases By to identify possible outliers."],
    output: ["Scatterplot."],
    report: ["Describe direction, approximate strength, linearity and any obvious outliers."],
    examSentence: "The scatterplot suggested a [positive/negative/no clear] approximately linear relationship between [x] and [y].",
    traps: ["Running correlation without checking whether the relationship is roughly linear."],
    sourceRefs: ["17-Lecture 6 Chunk 1.pdf p12"],
  },
  {
    id: "bivariate-correlation",
    category: "Correlation and linear regression",
    title: "Pearson or Spearman bivariate correlation",
    examUse: "Use this to quantify the direction and strength of association between two variables.",
    useWhen: ["Pearson: two continuous, roughly normal variables with linear relationship.", "Spearman: ordinal/skewed variables or non-parametric correlation."],
    variables: ["Two variables placed in Variables box."],
    menuPath: ["Analyze", "Correlate", "Bivariate"],
    setup: ["Move both variables into Variables.", "Choose Pearson or Spearman.", "Click OK."],
    options: ["Pearson for parametric linear correlation. Spearman for non-parametric/rank correlation."],
    output: ["Correlations table.", "Correlation coefficient.", "Sig. (2-tailed).", "N."],
    report: ["Report direction, strength and p-value."],
    examSentence: "There was a [weak/moderate/strong] [positive/negative] association between [x] and [y], r = [r], p = [p].",
    traps: ["Saying correlation proves causation.", "Using Pearson when the lecture asks for Spearman due to skewed data."],
    sourceRefs: ["18-Lecture 6 Chunk 2-slidesCorrected.pdf p11-p18"],
  },
  {
    id: "simple-linear-regression",
    category: "Correlation and linear regression",
    title: "Simple linear regression",
    examUse: "Use this when predicting a continuous outcome from one predictor.",
    useWhen: ["Outcome is continuous.", "One predictor is continuous or a 0/1 dummy variable.", "Question asks for slope, intercept or prediction."],
    variables: ["Dependent: continuous outcome.", "Independent(s): predictor variable."],
    menuPath: ["Analyze", "Regression", "Linear"],
    setup: ["Put the outcome into Dependent.", "Put the predictor into Independent(s).", "Click Statistics.", "Tick Estimates and Confidence intervals.", "Click Continue and OK."],
    options: ["Use Save if the question asks for predicted values or prediction intervals."],
    output: ["Model Summary.", "ANOVA.", "Coefficients table: B, t, Sig., CI."],
    report: ["Use unstandardized B for the regression equation and practical interpretation."],
    examSentence: "For every one-unit increase in [predictor], [outcome] changed by [B] units on average, p = [p].",
    traps: ["Interpreting the intercept when x = 0 is not meaningful.", "Using standardized Beta in the equation instead of B."],
    sourceRefs: ["19-Lecture 6 Chunk 3.pdf p14-p15"],
  },
  {
    id: "linear-prediction-save",
    category: "Correlation and linear regression",
    title: "Save predicted values from linear regression",
    examUse: "Use this when the exam asks for predicted values or prediction intervals.",
    useWhen: ["You need SPSS to calculate predicted values.", "A new x-value is added to the data set for prediction."],
    variables: ["Continuous outcome.", "Predictor variable.", "Optional new case with predictor value entered."],
    menuPath: ["Analyze", "Regression", "Linear", "Save"],
    setup: ["Run Linear regression as usual.", "Click Save.", "Select Prediction Values: Unstandardized.", "Select Prediction Intervals: Mean if needed.", "Click Continue and OK."],
    options: ["Add the x-value for the new case to the predictor column first if the lecture asks for prediction at a specific x."],
    output: ["New predicted-value column in the data set.", "Regression Coefficients table."],
    report: ["Use the saved predicted value or calculate from y = b0 + b1x."],
    examSentence: "The predicted value for [x] = [value] was [prediction].",
    traps: ["Forgetting to add the new predictor value before saving predicted values."],
    sourceRefs: ["19-Lecture 6 Chunk 3.pdf p21"],
  },
  {
    id: "multiple-linear-regression",
    category: "Correlation and linear regression",
    title: "Multiple linear regression and confounder adjustment",
    examUse: "Use this when a continuous outcome is predicted by several variables or an effect must be adjusted for confounders.",
    useWhen: ["Outcome is continuous.", "More than one predictor.", "Question says adjust, control for, confounder, or prediction model."],
    variables: ["Dependent: continuous outcome.", "Independent(s): exposure plus confounders/predictors."],
    menuPath: ["Analyze", "Regression", "Linear"],
    setup: ["Put outcome in Dependent.", "Put exposure and covariates in Independent(s).", "Click Statistics and tick Estimates, Model fit, R squared change if needed, Confidence intervals.", "Click OK."],
    options: ["Use the coefficient for the exposure after adding confounders for the adjusted association."],
    output: ["Model Summary: R2 and Adjusted R2.", "ANOVA: model p-value.", "Coefficients: adjusted B, p-value, CI."],
    report: ["State that the coefficient is adjusted for the other variables in the model."],
    examSentence: "After adjusting for [covariates], [predictor] was associated with a [B]-unit change in [outcome], p = [p].",
    traps: ["Calling an adjusted association causal without study-design support.", "Reading R2 as proof that the model is correct."],
    sourceRefs: ["23-lecture 7.pdf p14-p16", "20-lecture 7-2.pdf p10-p13", "21-lecture 7-3.pdf p10-p12"],
  },
  {
    id: "linear-regression-assumptions",
    category: "Correlation and linear regression",
    title: "Check linear regression assumptions",
    examUse: "Use this when the exam asks how to assess model assumptions or output plots.",
    useWhen: ["Linear or multiple linear regression.", "Question asks residuals, normality, homoscedasticity or partial plots."],
    variables: ["Regression outcome and predictors."],
    menuPath: ["Analyze", "Regression", "Linear", "Plots"],
    setup: [
      "Run Linear regression.",
      "Click Plots.",
      "Select Histogram.",
      "Select Normal probability plot.",
      "Select Produce all partial plots.",
      "Put ZRESID in Y and ZPRED in X for residual scatterplot.",
    ],
    options: ["Use Save if you need DFBETA/DFFIT or residual variables."],
    output: ["Histogram of residuals.", "Normal P-P plot.", "Partial plots.", "ZRESID versus ZPRED scatterplot."],
    report: ["Residuals should be roughly normal and show no clear pattern/funnel in residual plot."],
    examSentence: "The residual plot showed [no clear pattern/a pattern], suggesting [homoscedasticity/possible violation].",
    traps: ["Thinking linear regression requires the outcome itself to be normally distributed. The lecture emphasizes residual normality."],
    sourceRefs: ["22-lecture 7-4.pdf p3-p10"],
  },
  {
    id: "mediation-baron-kenny",
    category: "Mediation, interaction and outliers",
    title: "Mediation with Baron and Kenny regression steps",
    examUse: "Use this when the question asks whether X affects Y through a mediator M.",
    useWhen: ["There is an exposure X, mediator M and outcome Y.", "Outcome and mediator are suitable for linear regression in the lecture example."],
    variables: ["X: independent variable.", "M: mediator.", "Y: outcome."],
    menuPath: ["Analyze", "Regression", "Linear"],
    setup: [
      "Path c: run Y on X.",
      "Path a: run M on X.",
      "Path b and c': run Y on M and X together.",
      "Read the relevant coefficients and p-values.",
    ],
    options: ["Use three regression models from the same Linear Regression menu."],
    output: ["Coefficients table for path c.", "Coefficients table for path a.", "Coefficients table for paths b and c'."],
    report: ["Partial mediation: c' becomes smaller but remains significant. Complete mediation: c' becomes non-significant after M is included."],
    examSentence: "The indirect pathway was supported because X predicted M, and M predicted Y after controlling for X.",
    traps: ["Calling something a mediator when it is not in the causal pathway.", "Forgetting that path b is tested while controlling for X."],
    sourceRefs: ["25-lecture 8-2.pdf p4-p19"],
  },
  {
    id: "process-macro",
    category: "Mediation, interaction and outliers",
    title: "PROCESS macro for indirect effect",
    examUse: "Use this when the lecture asks for bootstrap confidence intervals for mediation.",
    useWhen: ["The exam mentions PROCESS, Model 4, bootstrap, indirect effect or ab.", "You need a confidence interval for the indirect effect."],
    variables: ["Outcome Y.", "Independent variable X.", "Mediator M."],
    menuPath: ["Analyze", "Regression", "PROCESS"],
    setup: ["Shorten variable names to 8 characters if needed.", "Put Y in Outcome.", "Put X in Independent Variable.", "Put M in M Variable(s).", "Choose Model 4.", "Run."],
    options: ["If PROCESS is not installed: Extensions > Utilities > Install Custom Dialog for process.spd, or run process.sps syntax."],
    output: ["Indirect effect estimate ab.", "Bootstrap confidence interval."],
    report: ["If the bootstrap CI for ab excludes 0, the indirect effect is significant."],
    examSentence: "The indirect effect was [significant/not significant] because the bootstrap confidence interval [excluded/included] 0.",
    traps: ["Using 1 as the null value for mediation CI. For indirect effects, the null value is 0."],
    sourceRefs: ["26-lecture 8-3.pdf p8-p13"],
  },
  {
    id: "interaction-linear",
    category: "Mediation, interaction and outliers",
    title: "Interaction / moderation in linear regression",
    examUse: "Use this when the effect of X on Y may differ by a moderator Z.",
    useWhen: ["Question says effect modification, moderation, interaction, stronger/weaker by subgroup, or depends on.", "You need a product term."],
    variables: ["Outcome Y.", "Predictor X.", "Moderator Z.", "Interaction term X_Z."],
    menuPath: ["Transform", "Compute Variable", "then Analyze", "Regression", "Linear"],
    setup: [
      "Compute X_Z as X * Z.",
      "Run Linear regression.",
      "Put Y in Dependent.",
      "Put X, Z and X_Z in Independent(s).",
      "Read the p-value for X_Z.",
    ],
    options: ["For a categorical moderator with 3+ categories, create dummy variables first and use products with each dummy."],
    output: ["Coefficients table.", "B and Sig. for the interaction term."],
    report: ["A significant interaction term supports effect modification."],
    examSentence: "There was evidence of interaction because the product term was significant, B = [B], p = [p].",
    traps: ["Interpreting only the main effect when the interaction is significant.", "Forgetting dummy variables for a 3+ category moderator."],
    sourceRefs: ["27-lecture 9-1.pdf p6-p11", "01-Lecture 9 Chunk 2.pdf p8-p10/p15-p22"],
  },
  {
    id: "dfbeta-dffit",
    category: "Mediation, interaction and outliers",
    title: "Save DFBETA and DFFIT for influential cases",
    examUse: "Use this when the question asks whether outliers are influential in regression.",
    useWhen: ["Regression model has a suspected influential point.", "Lecture asks for DFBETA or DFFIT."],
    variables: ["Continuous outcome.", "Predictor(s)."],
    menuPath: ["Analyze", "Regression", "Linear", "Save"],
    setup: ["Run Linear regression.", "Click Save.", "Select DFBETA and DFFIT options.", "Click Continue and OK.", "Inspect saved variables in the data set."],
    options: ["The lecture uses absolute values above 1 as a simple influence flag."],
    output: ["Saved DFBETA variables.", "Saved DFFIT variable.", "Regression output."],
    report: ["A large DFBETA/DFFIT suggests the case changes the model noticeably."],
    examSentence: "The case appeared influential because its absolute [DFBETA/DFFIT] exceeded the lecture threshold.",
    traps: ["Treating every outlier as influential. Outlier means unusual; influential means it changes the fitted model."],
    sourceRefs: ["02-lecture 9 Chunk 3 QAC.pdf p18-p19"],
  },
  {
    id: "binary-logistic-basic",
    category: "Binary logistic regression",
    title: "Binary logistic regression",
    examUse: "Use this when the outcome is binary and the question asks for prediction, odds, Exp(B), or adjustment.",
    useWhen: ["Dependent variable is yes/no or 0/1.", "Predictors can be continuous or categorical.", "Question asks for odds ratio or adjusted odds ratio."],
    variables: ["Dependent: binary outcome.", "Covariates: predictors."],
    menuPath: ["Analyze", "Regression", "Binary Logistic"],
    setup: ["Put the binary outcome in Dependent.", "Put predictors in Covariates.", "Click Categorical for categorical predictors.", "Set reference category and click Change.", "Click Options and tick CI for Exp(B).", "Click OK."],
    options: ["Use Enter method unless the lecture/exam says otherwise.", "For categorical predictors, always check the reference category."],
    output: ["Omnibus Tests of Model Coefficients.", "Model Summary: Nagelkerke R2.", "Variables in the Equation: B, Sig., Exp(B), CI."],
    report: ["Use Exp(B) as the odds ratio. Use Sig. for p-value. CI for Exp(B) including 1 means not significant."],
    examSentence: "[Group/predictor] had [Exp(B)] times the odds of [event] compared with [reference], p = [p].",
    traps: ["Interpreting B as the odds ratio.", "Forgetting to define categorical predictors and reference category."],
    sourceRefs: ["29-lecture 10-2.pdf p20-p22", "30-lecture 10-3.pdf p6-p9"],
  },
  {
    id: "binary-logistic-adjusted",
    category: "Binary logistic regression",
    title: "Adjusted binary logistic regression",
    examUse: "Use this when the question says adjusting for, controlling for, covariates or confounders with a binary outcome.",
    useWhen: ["Outcome is binary.", "Need adjusted odds ratio.", "There is a potential confounder/covariate."],
    variables: ["Binary dependent variable.", "Exposure of interest.", "Covariates/confounders."],
    menuPath: ["Analyze", "Regression", "Binary Logistic"],
    setup: ["Put binary outcome in Dependent.", "Put exposure plus covariates in Covariates.", "Define categorical predictors.", "Options: tick CI for Exp(B).", "Run."],
    options: ["Interpret the exposure Exp(B) as adjusted for the other covariates."],
    output: ["Omnibus Tests.", "Nagelkerke R2.", "Variables in the Equation.", "Exp(B) and CI."],
    report: ["Say 'adjusting for' or 'holding other variables constant'."],
    examSentence: "After adjusting for [covariate], [exposure] had [Exp(B)] times the odds of [outcome] compared with [reference].",
    traps: ["Reporting the unadjusted odds ratio when the question asks for adjusted odds ratio."],
    sourceRefs: ["30-lecture 10-3.pdf p4-p11"],
  },
  {
    id: "logistic-classification",
    category: "Binary logistic regression",
    title: "Classification table, sensitivity, specificity, PPV and NPV",
    examUse: "Use this when the exam asks how well a logistic model predicts cases/non-cases.",
    useWhen: ["Binary logistic regression output includes Classification Table.", "Question asks sensitivity, specificity, PPV, NPV or cut-off."],
    variables: ["Binary observed outcome.", "Predicted outcome from logistic model."],
    menuPath: ["Analyze", "Regression", "Binary Logistic", "Options"],
    setup: ["Set up Binary Logistic regression.", "Click Options.", "Tick Classification plots if needed.", "Use the classification cutoff shown by SPSS, often .5 unless changed.", "Run."],
    options: ["Classification metrics depend on which category is coded as the event."],
    output: ["Classification Table.", "Observed versus Predicted counts.", "Overall percentage.", "Cut Value."],
    report: ["Sensitivity = TP/(TP+FN). Specificity = TN/(TN+FP). PPV = TP/(TP+FP). NPV = TN/(TN+FN)."],
    examSentence: "The model correctly classified [overall]%. Sensitivity was [sens]% and specificity was [spec]%.",
    traps: ["Mixing up predicted positive with observed positive.", "Assuming high overall accuracy means good sensitivity."],
    sourceRefs: ["31-lecture 10-4.pdf p11-p19"],
  },
  {
    id: "hosmer-lemeshow",
    category: "Binary logistic regression",
    title: "Hosmer-Lemeshow goodness of fit",
    examUse: "Use this when the exam asks whether the logistic regression model fits adequately.",
    useWhen: ["Binary logistic regression.", "Question asks goodness of fit or Hosmer-Lemeshow."],
    variables: ["Binary outcome.", "Predictors in logistic model."],
    menuPath: ["Analyze", "Regression", "Binary Logistic", "Options"],
    setup: ["Set up Binary Logistic regression.", "Click Options.", "Tick Hosmer-Lemeshow goodness-of-fit.", "Run."],
    options: ["Read this differently from usual p-values."],
    output: ["Hosmer and Lemeshow Test table.", "Chi-square, df, Sig."],
    report: ["p > .05 suggests adequate fit. p < .05 suggests poor fit."],
    examSentence: "The Hosmer-Lemeshow test was non-significant, p = [p], suggesting no evidence of poor model fit.",
    traps: ["Applying the usual p < .05 is good rule. For Hosmer-Lemeshow, non-significant is reassuring."],
    sourceRefs: ["31-lecture 10-4.pdf p21-p22"],
  },
];
